### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by jtpdev** [vikdiesel/admin-one-laravel-dashboard#6]
I'm trying to follow the instructions in the **Quick Start** section of the read.me.
But in the fourth step the exception is thrown: **Could not open input file: artisan**.
The file *artisan* doesn't exists, and it isn't created with **composer require laravel/ui** or, after did it, **composer install/update**.

I'm using Ubuntu 18 and I did permission to create in the directory.

**Comment by vikdiesel** [comment]
Laravel should be [installed](https://laravel.com/docs/7.x/installation) before running **Quick Start** section.

**Comment by jtpdev** [comment]
Laravel has already been installed:

![image](https://user-images.githubusercontent.com/28665598/84814059-4a796f80-afe7-11ea-91b6-208f77c46efb.png)

**Comment by jtpdev** [comment]
It's a pebcak problem. Everything works very well.
